# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ejson-rails` gem.
# Please instead update this file by running `tapioca sync`.

# typed: true

module EJSON
end

module EJSON::Rails
end

class EJSON::Rails::Railtie < ::Rails::Railtie
  class << self

    private

    def json_files; end
    def valid?(pathname); end
  end
end
