# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `tapioca require`.

# typed: false

require 'action_cable/engine'
require 'action_controller/railtie'
require 'action_mailbox/engine'
require 'action_mailer/railtie'
require 'action_text/engine'
require 'action_view/railtie'
require 'active_job/railtie'
require 'active_model/railtie'
require 'active_record/railtie'
require 'active_storage/engine'
require 'bootsnap/setup'
require 'bundler/setup'
require 'mocha/minitest'
require 'rails'
require 'rails/test_help'
require 'rails/test_unit/railtie'
