# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApiController`.
# Please instead update this file by running `tapioca dsl`.

# typed: true
class ApiController
  include GeneratedPathHelpersModule
  include GeneratedUrlHelpersModule
end