# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApplicationController`.
# Please instead update this file by running `tapioca dsl`.

# typed: true
class ApplicationController
  include GeneratedPathHelpersModule
  include GeneratedUrlHelpersModule
end