default: &default
  adapter: postgresql
  host: localhost
  username: fyi
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: fyi_production
  password: <%= ENV['FYI_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: fyi_development

test:
  <<: *default
  database: fyi_test
